/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.models.components.VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
import org.openapis.openapi.utils.Response;
import org.openapis.openapi.utils.Utils;


public class CreateDialingPermissionsCountryBulkUpdateResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Created
     */
    private Optional<? extends VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;

    private Map<String, List<String>> headers;

    @JsonCreator
    public CreateDialingPermissionsCountryBulkUpdateResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate,
            Map<String, List<String>> headers) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate");
        headers = Utils.emptyMapIfNull(headers);
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
        this.headers = headers;
    }
    
    public CreateDialingPermissionsCountryBulkUpdateResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Map<String, List<String>> headers) {
        this(contentType, statusCode, rawResponse, Optional.empty(), headers);
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Created
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate() {
        return (Optional<VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate>) voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
    }

    @JsonIgnore
    public Map<String, List<String>> headers() {
        return headers;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public CreateDialingPermissionsCountryBulkUpdateResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateDialingPermissionsCountryBulkUpdateResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateDialingPermissionsCountryBulkUpdateResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Created
     */
    public CreateDialingPermissionsCountryBulkUpdateResponse withVoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate(VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate) {
        Utils.checkNotNull(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate");
        this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = Optional.ofNullable(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate);
        return this;
    }

    /**
     * Created
     */
    public CreateDialingPermissionsCountryBulkUpdateResponse withVoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate(Optional<? extends VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate) {
        Utils.checkNotNull(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate");
        this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
        return this;
    }

    public CreateDialingPermissionsCountryBulkUpdateResponse withHeaders(Map<String, List<String>> headers) {
        Utils.checkNotNull(headers, "headers");
        this.headers = headers;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDialingPermissionsCountryBulkUpdateResponse other = (CreateDialingPermissionsCountryBulkUpdateResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, other.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate) &&
            Objects.deepEquals(this.headers, other.headers);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate,
            headers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateDialingPermissionsCountryBulkUpdateResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate", voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate,
                "headers", headers);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = Optional.empty();
 
        private Map<String, List<String>> headers;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Created
         */
        public Builder voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate(VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate) {
            Utils.checkNotNull(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate");
            this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = Optional.ofNullable(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate);
            return this;
        }

        /**
         * Created
         */
        public Builder voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate(Optional<? extends VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate> voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate) {
            Utils.checkNotNull(voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate, "voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate");
            this.voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate = voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
            return this;
        }

        public Builder headers(Map<String, List<String>> headers) {
            Utils.checkNotNull(headers, "headers");
            this.headers = headers;
            return this;
        }
        
        public CreateDialingPermissionsCountryBulkUpdateResponse build() {
            return new CreateDialingPermissionsCountryBulkUpdateResponse(
                contentType,
                statusCode,
                rawResponse,
                voiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate,
                headers);
        }
    }
}

