/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class CreateSourceIpMappingCreateSourceIpMappingRequest {

    /**
     * The Twilio-provided string that uniquely identifies the IP Record resource to map from.
     */
    @SpeakeasyMetadata("form:name=IpRecordSid")
    private String ipRecordSid;

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    @SpeakeasyMetadata("form:name=SipDomainSid")
    private String sipDomainSid;

    @JsonCreator
    public CreateSourceIpMappingCreateSourceIpMappingRequest(
            String ipRecordSid,
            String sipDomainSid) {
        Utils.checkNotNull(ipRecordSid, "ipRecordSid");
        Utils.checkNotNull(sipDomainSid, "sipDomainSid");
        this.ipRecordSid = ipRecordSid;
        this.sipDomainSid = sipDomainSid;
    }

    /**
     * The Twilio-provided string that uniquely identifies the IP Record resource to map from.
     */
    @JsonIgnore
    public String ipRecordSid() {
        return ipRecordSid;
    }

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    @JsonIgnore
    public String sipDomainSid() {
        return sipDomainSid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The Twilio-provided string that uniquely identifies the IP Record resource to map from.
     */
    public CreateSourceIpMappingCreateSourceIpMappingRequest withIpRecordSid(String ipRecordSid) {
        Utils.checkNotNull(ipRecordSid, "ipRecordSid");
        this.ipRecordSid = ipRecordSid;
        return this;
    }

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    public CreateSourceIpMappingCreateSourceIpMappingRequest withSipDomainSid(String sipDomainSid) {
        Utils.checkNotNull(sipDomainSid, "sipDomainSid");
        this.sipDomainSid = sipDomainSid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateSourceIpMappingCreateSourceIpMappingRequest other = (CreateSourceIpMappingCreateSourceIpMappingRequest) o;
        return 
            Objects.deepEquals(this.ipRecordSid, other.ipRecordSid) &&
            Objects.deepEquals(this.sipDomainSid, other.sipDomainSid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            ipRecordSid,
            sipDomainSid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateSourceIpMappingCreateSourceIpMappingRequest.class,
                "ipRecordSid", ipRecordSid,
                "sipDomainSid", sipDomainSid);
    }
    
    public final static class Builder {
 
        private String ipRecordSid;
 
        private String sipDomainSid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Twilio-provided string that uniquely identifies the IP Record resource to map from.
         */
        public Builder ipRecordSid(String ipRecordSid) {
            Utils.checkNotNull(ipRecordSid, "ipRecordSid");
            this.ipRecordSid = ipRecordSid;
            return this;
        }

        /**
         * The SID of the SIP Domain that the IP Record should be mapped to.
         */
        public Builder sipDomainSid(String sipDomainSid) {
            Utils.checkNotNull(sipDomainSid, "sipDomainSid");
            this.sipDomainSid = sipDomainSid;
            return this;
        }
        
        public CreateSourceIpMappingCreateSourceIpMappingRequest build() {
            return new CreateSourceIpMappingCreateSourceIpMappingRequest(
                ipRecordSid,
                sipDomainSid);
        }
    }
}

