/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest {

    /**
     * URL encoded JSON array of update objects. example : `[ { "iso_code": "GB", "low_risk_numbers_enabled": "true", "high_risk_special_numbers_enabled":"true", "high_risk_tollfraud_numbers_enabled": "false" } ]`
     */
    @SpeakeasyMetadata("form:name=UpdateRequest")
    private String updateRequest;

    @JsonCreator
    public CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest(
            String updateRequest) {
        Utils.checkNotNull(updateRequest, "updateRequest");
        this.updateRequest = updateRequest;
    }

    /**
     * URL encoded JSON array of update objects. example : `[ { "iso_code": "GB", "low_risk_numbers_enabled": "true", "high_risk_special_numbers_enabled":"true", "high_risk_tollfraud_numbers_enabled": "false" } ]`
     */
    @JsonIgnore
    public String updateRequest() {
        return updateRequest;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * URL encoded JSON array of update objects. example : `[ { "iso_code": "GB", "low_risk_numbers_enabled": "true", "high_risk_special_numbers_enabled":"true", "high_risk_tollfraud_numbers_enabled": "false" } ]`
     */
    public CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest withUpdateRequest(String updateRequest) {
        Utils.checkNotNull(updateRequest, "updateRequest");
        this.updateRequest = updateRequest;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest other = (CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest) o;
        return 
            Objects.deepEquals(this.updateRequest, other.updateRequest);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            updateRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest.class,
                "updateRequest", updateRequest);
    }
    
    public final static class Builder {
 
        private String updateRequest;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * URL encoded JSON array of update objects. example : `[ { "iso_code": "GB", "low_risk_numbers_enabled": "true", "high_risk_special_numbers_enabled":"true", "high_risk_tollfraud_numbers_enabled": "false" } ]`
         */
        public Builder updateRequest(String updateRequest) {
            Utils.checkNotNull(updateRequest, "updateRequest");
            this.updateRequest = updateRequest;
            return this;
        }
        
        public CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest build() {
            return new CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest(
                updateRequest);
        }
    }
}

