/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class CreateByocTrunkRequestBuilder {

    private Optional<? extends CreateByocTrunkCreateByocTrunkRequest> request = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallCreateByocTrunk sdk;

    public CreateByocTrunkRequestBuilder(SDKMethodInterfaces.MethodCallCreateByocTrunk sdk) {
        this.sdk = sdk;
    }
                
    public CreateByocTrunkRequestBuilder request(CreateByocTrunkCreateByocTrunkRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public CreateByocTrunkRequestBuilder request(Optional<? extends CreateByocTrunkCreateByocTrunkRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public CreateByocTrunkRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public CreateByocTrunkRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public CreateByocTrunkResponse call() throws Exception {

        return sdk.createByocTrunk(
            request,
            serverURL);
    }
}
