/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class CreateConnectionPolicyRequestBuilder {

    private Optional<? extends CreateConnectionPolicyCreateConnectionPolicyRequest> request = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallCreateConnectionPolicy sdk;

    public CreateConnectionPolicyRequestBuilder(SDKMethodInterfaces.MethodCallCreateConnectionPolicy sdk) {
        this.sdk = sdk;
    }
                
    public CreateConnectionPolicyRequestBuilder request(CreateConnectionPolicyCreateConnectionPolicyRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public CreateConnectionPolicyRequestBuilder request(Optional<? extends CreateConnectionPolicyCreateConnectionPolicyRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public CreateConnectionPolicyRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public CreateConnectionPolicyRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public CreateConnectionPolicyResponse call() throws Exception {

        return sdk.createConnectionPolicy(
            request,
            serverURL);
    }
}
