/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.time.LocalDate;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class DeleteArchivedCallRequest {

    /**
     * The date of the Call in UTC.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Date")
    private LocalDate date;

    /**
     * The Twilio-provided Call SID that uniquely identifies the Call resource to delete
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    private String sid;

    @JsonCreator
    public DeleteArchivedCallRequest(
            LocalDate date,
            String sid) {
        Utils.checkNotNull(date, "date");
        Utils.checkNotNull(sid, "sid");
        this.date = date;
        this.sid = sid;
    }

    /**
     * The date of the Call in UTC.
     */
    @JsonIgnore
    public LocalDate date() {
        return date;
    }

    /**
     * The Twilio-provided Call SID that uniquely identifies the Call resource to delete
     */
    @JsonIgnore
    public String sid() {
        return sid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The date of the Call in UTC.
     */
    public DeleteArchivedCallRequest withDate(LocalDate date) {
        Utils.checkNotNull(date, "date");
        this.date = date;
        return this;
    }

    /**
     * The Twilio-provided Call SID that uniquely identifies the Call resource to delete
     */
    public DeleteArchivedCallRequest withSid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteArchivedCallRequest other = (DeleteArchivedCallRequest) o;
        return 
            Objects.deepEquals(this.date, other.date) &&
            Objects.deepEquals(this.sid, other.sid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            date,
            sid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteArchivedCallRequest.class,
                "date", date,
                "sid", sid);
    }
    
    public final static class Builder {
 
        private LocalDate date;
 
        private String sid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The date of the Call in UTC.
         */
        public Builder date(LocalDate date) {
            Utils.checkNotNull(date, "date");
            this.date = date;
            return this;
        }

        /**
         * The Twilio-provided Call SID that uniquely identifies the Call resource to delete
         */
        public Builder sid(String sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = sid;
            return this;
        }
        
        public DeleteArchivedCallRequest build() {
            return new DeleteArchivedCallRequest(
                date,
                sid);
        }
    }
}

