/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class DeleteByocTrunkRequest {

    /**
     * The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    private String sid;

    @JsonCreator
    public DeleteByocTrunkRequest(
            String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
    }

    /**
     * The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete.
     */
    @JsonIgnore
    public String sid() {
        return sid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete.
     */
    public DeleteByocTrunkRequest withSid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteByocTrunkRequest other = (DeleteByocTrunkRequest) o;
        return 
            Objects.deepEquals(this.sid, other.sid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            sid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteByocTrunkRequest.class,
                "sid", sid);
    }
    
    public final static class Builder {
 
        private String sid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Twilio-provided string that uniquely identifies the BYOC Trunk resource to delete.
         */
        public Builder sid(String sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = sid;
            return this;
        }
        
        public DeleteByocTrunkRequest build() {
            return new DeleteByocTrunkRequest(
                sid);
        }
    }
}

