/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class DeleteConnectionPolicyTargetRequest {

    /**
     * The SID of the Connection Policy that owns the Target.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ConnectionPolicySid")
    private String connectionPolicySid;

    /**
     * The unique string that we created to identify the Target resource to delete.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    private String sid;

    @JsonCreator
    public DeleteConnectionPolicyTargetRequest(
            String connectionPolicySid,
            String sid) {
        Utils.checkNotNull(connectionPolicySid, "connectionPolicySid");
        Utils.checkNotNull(sid, "sid");
        this.connectionPolicySid = connectionPolicySid;
        this.sid = sid;
    }

    /**
     * The SID of the Connection Policy that owns the Target.
     */
    @JsonIgnore
    public String connectionPolicySid() {
        return connectionPolicySid;
    }

    /**
     * The unique string that we created to identify the Target resource to delete.
     */
    @JsonIgnore
    public String sid() {
        return sid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The SID of the Connection Policy that owns the Target.
     */
    public DeleteConnectionPolicyTargetRequest withConnectionPolicySid(String connectionPolicySid) {
        Utils.checkNotNull(connectionPolicySid, "connectionPolicySid");
        this.connectionPolicySid = connectionPolicySid;
        return this;
    }

    /**
     * The unique string that we created to identify the Target resource to delete.
     */
    public DeleteConnectionPolicyTargetRequest withSid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteConnectionPolicyTargetRequest other = (DeleteConnectionPolicyTargetRequest) o;
        return 
            Objects.deepEquals(this.connectionPolicySid, other.connectionPolicySid) &&
            Objects.deepEquals(this.sid, other.sid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            connectionPolicySid,
            sid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteConnectionPolicyTargetRequest.class,
                "connectionPolicySid", connectionPolicySid,
                "sid", sid);
    }
    
    public final static class Builder {
 
        private String connectionPolicySid;
 
        private String sid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The SID of the Connection Policy that owns the Target.
         */
        public Builder connectionPolicySid(String connectionPolicySid) {
            Utils.checkNotNull(connectionPolicySid, "connectionPolicySid");
            this.connectionPolicySid = connectionPolicySid;
            return this;
        }

        /**
         * The unique string that we created to identify the Target resource to delete.
         */
        public Builder sid(String sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = sid;
            return this;
        }
        
        public DeleteConnectionPolicyTargetRequest build() {
            return new DeleteConnectionPolicyTargetRequest(
                connectionPolicySid,
                sid);
        }
    }
}

