/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class FetchConnectionPolicyRequestBuilder {

    private String sid;
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallFetchConnectionPolicy sdk;

    public FetchConnectionPolicyRequestBuilder(SDKMethodInterfaces.MethodCallFetchConnectionPolicy sdk) {
        this.sdk = sdk;
    }

    public FetchConnectionPolicyRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public FetchConnectionPolicyRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public FetchConnectionPolicyRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public FetchConnectionPolicyResponse call() throws Exception {

        return sdk.fetchConnectionPolicy(
            sid,
            serverURL);
    }
}
