/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class FetchDialingPermissionsCountryRequestBuilder {

    private String isoCode;
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallFetchDialingPermissionsCountry sdk;

    public FetchDialingPermissionsCountryRequestBuilder(SDKMethodInterfaces.MethodCallFetchDialingPermissionsCountry sdk) {
        this.sdk = sdk;
    }

    public FetchDialingPermissionsCountryRequestBuilder isoCode(String isoCode) {
        Utils.checkNotNull(isoCode, "isoCode");
        this.isoCode = isoCode;
        return this;
    }
                
    public FetchDialingPermissionsCountryRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public FetchDialingPermissionsCountryRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public FetchDialingPermissionsCountryResponse call() throws Exception {

        return sdk.fetchDialingPermissionsCountry(
            isoCode,
            serverURL);
    }
}
