/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class FetchByocTrunkRequestBuilder {

    private String sid;
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallFetchByocTrunk sdk;

    public FetchByocTrunkRequestBuilder(SDKMethodInterfaces.MethodCallFetchByocTrunk sdk) {
        this.sdk = sdk;
    }

    public FetchByocTrunkRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public FetchByocTrunkRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public FetchByocTrunkRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public FetchByocTrunkResponse call() throws Exception {

        return sdk.fetchByocTrunk(
            sid,
            serverURL);
    }
}
