/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class FetchDialingPermissionsSettingsRequestBuilder {

    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallFetchDialingPermissionsSettings sdk;

    public FetchDialingPermissionsSettingsRequestBuilder(SDKMethodInterfaces.MethodCallFetchDialingPermissionsSettings sdk) {
        this.sdk = sdk;
    }
                
    public FetchDialingPermissionsSettingsRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public FetchDialingPermissionsSettingsRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public FetchDialingPermissionsSettingsResponse call() throws Exception {

        return sdk.fetchDialingPermissionsSettings(
            serverURL);
    }
}
