/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListByocTrunkRequestBuilder {

    private Optional<Long> pageSize = Optional.empty();
    private Optional<Long> page = Optional.empty();
    private Optional<String> pageToken = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListByocTrunk sdk;

    public ListByocTrunkRequestBuilder(SDKMethodInterfaces.MethodCallListByocTrunk sdk) {
        this.sdk = sdk;
    }
                
    public ListByocTrunkRequestBuilder pageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.of(pageSize);
        return this;
    }

    public ListByocTrunkRequestBuilder pageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }
                
    public ListByocTrunkRequestBuilder page(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.of(page);
        return this;
    }

    public ListByocTrunkRequestBuilder page(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }
                
    public ListByocTrunkRequestBuilder pageToken(String pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = Optional.of(pageToken);
        return this;
    }

    public ListByocTrunkRequestBuilder pageToken(Optional<String> pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = pageToken;
        return this;
    }
                
    public ListByocTrunkRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public ListByocTrunkRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public ListByocTrunkResponse call() throws Exception {

        return sdk.listByocTrunk(
            pageSize,
            page,
            pageToken,
            serverURL);
    }
}
