/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListDialingPermissionsHrsPrefixesRequestBuilder {

    private String isoCode;
    private Optional<Long> pageSize = Optional.empty();
    private Optional<Long> page = Optional.empty();
    private Optional<String> pageToken = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListDialingPermissionsHrsPrefixes sdk;

    public ListDialingPermissionsHrsPrefixesRequestBuilder(SDKMethodInterfaces.MethodCallListDialingPermissionsHrsPrefixes sdk) {
        this.sdk = sdk;
    }

    public ListDialingPermissionsHrsPrefixesRequestBuilder isoCode(String isoCode) {
        Utils.checkNotNull(isoCode, "isoCode");
        this.isoCode = isoCode;
        return this;
    }
                
    public ListDialingPermissionsHrsPrefixesRequestBuilder pageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.of(pageSize);
        return this;
    }

    public ListDialingPermissionsHrsPrefixesRequestBuilder pageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }
                
    public ListDialingPermissionsHrsPrefixesRequestBuilder page(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.of(page);
        return this;
    }

    public ListDialingPermissionsHrsPrefixesRequestBuilder page(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }
                
    public ListDialingPermissionsHrsPrefixesRequestBuilder pageToken(String pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = Optional.of(pageToken);
        return this;
    }

    public ListDialingPermissionsHrsPrefixesRequestBuilder pageToken(Optional<String> pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = pageToken;
        return this;
    }
                
    public ListDialingPermissionsHrsPrefixesRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public ListDialingPermissionsHrsPrefixesRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public ListDialingPermissionsHrsPrefixesResponse call() throws Exception {

        return sdk.listDialingPermissionsHrsPrefixes(
            isoCode,
            pageSize,
            page,
            pageToken,
            serverURL);
    }
}
