/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListDialingPermissionsCountryRequestBuilder {

    private ListDialingPermissionsCountryRequest request;
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListDialingPermissionsCountry sdk;

    public ListDialingPermissionsCountryRequestBuilder(SDKMethodInterfaces.MethodCallListDialingPermissionsCountry sdk) {
        this.sdk = sdk;
    }

    public ListDialingPermissionsCountryRequestBuilder request(ListDialingPermissionsCountryRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public ListDialingPermissionsCountryRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public ListDialingPermissionsCountryRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public ListDialingPermissionsCountryResponse call() throws Exception {

        return sdk.listDialingPermissionsCountry(
            request,
            serverURL);
    }
}
