/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.Long;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class ListIpRecordRequestBuilder {

    private Optional<Long> pageSize = Optional.empty();
    private Optional<Long> page = Optional.empty();
    private Optional<String> pageToken = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListIpRecord sdk;

    public ListIpRecordRequestBuilder(SDKMethodInterfaces.MethodCallListIpRecord sdk) {
        this.sdk = sdk;
    }
                
    public ListIpRecordRequestBuilder pageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.of(pageSize);
        return this;
    }

    public ListIpRecordRequestBuilder pageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }
                
    public ListIpRecordRequestBuilder page(long page) {
        Utils.checkNotNull(page, "page");
        this.page = Optional.of(page);
        return this;
    }

    public ListIpRecordRequestBuilder page(Optional<Long> page) {
        Utils.checkNotNull(page, "page");
        this.page = page;
        return this;
    }
                
    public ListIpRecordRequestBuilder pageToken(String pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = Optional.of(pageToken);
        return this;
    }

    public ListIpRecordRequestBuilder pageToken(Optional<String> pageToken) {
        Utils.checkNotNull(pageToken, "pageToken");
        this.pageToken = pageToken;
        return this;
    }
                
    public ListIpRecordRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public ListIpRecordRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public ListIpRecordResponse call() throws Exception {

        return sdk.listIpRecord(
            pageSize,
            page,
            pageToken,
            serverURL);
    }
}
