/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class UpdateByocTrunkRequestBuilder {

    private String sid;
    private Optional<? extends UpdateByocTrunkUpdateByocTrunkRequest> requestBody = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateByocTrunk sdk;

    public UpdateByocTrunkRequestBuilder(SDKMethodInterfaces.MethodCallUpdateByocTrunk sdk) {
        this.sdk = sdk;
    }

    public UpdateByocTrunkRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public UpdateByocTrunkRequestBuilder requestBody(UpdateByocTrunkUpdateByocTrunkRequest requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.of(requestBody);
        return this;
    }

    public UpdateByocTrunkRequestBuilder requestBody(Optional<? extends UpdateByocTrunkUpdateByocTrunkRequest> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
                
    public UpdateByocTrunkRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public UpdateByocTrunkRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public UpdateByocTrunkResponse call() throws Exception {

        return sdk.updateByocTrunk(
            sid,
            requestBody,
            serverURL);
    }
}
