/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class UpdateConnectionPolicyRequestBuilder {

    private String sid;
    private Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateConnectionPolicy sdk;

    public UpdateConnectionPolicyRequestBuilder(SDKMethodInterfaces.MethodCallUpdateConnectionPolicy sdk) {
        this.sdk = sdk;
    }

    public UpdateConnectionPolicyRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public UpdateConnectionPolicyRequestBuilder requestBody(UpdateConnectionPolicyUpdateConnectionPolicyRequest requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.of(requestBody);
        return this;
    }

    public UpdateConnectionPolicyRequestBuilder requestBody(Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
                
    public UpdateConnectionPolicyRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public UpdateConnectionPolicyRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public UpdateConnectionPolicyResponse call() throws Exception {

        return sdk.updateConnectionPolicy(
            sid,
            requestBody,
            serverURL);
    }
}
