/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class UpdateSourceIpMappingUpdateSourceIpMappingRequest {

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    @SpeakeasyMetadata("form:name=SipDomainSid")
    private String sipDomainSid;

    @JsonCreator
    public UpdateSourceIpMappingUpdateSourceIpMappingRequest(
            String sipDomainSid) {
        Utils.checkNotNull(sipDomainSid, "sipDomainSid");
        this.sipDomainSid = sipDomainSid;
    }

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    @JsonIgnore
    public String sipDomainSid() {
        return sipDomainSid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The SID of the SIP Domain that the IP Record should be mapped to.
     */
    public UpdateSourceIpMappingUpdateSourceIpMappingRequest withSipDomainSid(String sipDomainSid) {
        Utils.checkNotNull(sipDomainSid, "sipDomainSid");
        this.sipDomainSid = sipDomainSid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateSourceIpMappingUpdateSourceIpMappingRequest other = (UpdateSourceIpMappingUpdateSourceIpMappingRequest) o;
        return 
            Objects.deepEquals(this.sipDomainSid, other.sipDomainSid);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            sipDomainSid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateSourceIpMappingUpdateSourceIpMappingRequest.class,
                "sipDomainSid", sipDomainSid);
    }
    
    public final static class Builder {
 
        private String sipDomainSid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The SID of the SIP Domain that the IP Record should be mapped to.
         */
        public Builder sipDomainSid(String sipDomainSid) {
            Utils.checkNotNull(sipDomainSid, "sipDomainSid");
            this.sipDomainSid = sipDomainSid;
            return this;
        }
        
        public UpdateSourceIpMappingUpdateSourceIpMappingRequest build() {
            return new UpdateSourceIpMappingUpdateSourceIpMappingRequest(
                sipDomainSid);
        }
    }
}

