/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest {

    /**
     * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
     */
    @SpeakeasyMetadata("form:name=FriendlyName")
    private Optional<String> friendlyName;

    /**
     * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
     */
    @SpeakeasyMetadata("form:name=Target")
    private Optional<String> target;

    /**
     * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
     */
    @SpeakeasyMetadata("form:name=Priority")
    private Optional<Long> priority;

    /**
     * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
     */
    @SpeakeasyMetadata("form:name=Weight")
    private Optional<Long> weight;

    /**
     * Whether the Target is enabled.
     */
    @SpeakeasyMetadata("form:name=Enabled")
    private Optional<Boolean> enabled;

    @JsonCreator
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest(
            Optional<String> friendlyName,
            Optional<String> target,
            Optional<Long> priority,
            Optional<Long> weight,
            Optional<Boolean> enabled) {
        Utils.checkNotNull(friendlyName, "friendlyName");
        Utils.checkNotNull(target, "target");
        Utils.checkNotNull(priority, "priority");
        Utils.checkNotNull(weight, "weight");
        Utils.checkNotNull(enabled, "enabled");
        this.friendlyName = friendlyName;
        this.target = target;
        this.priority = priority;
        this.weight = weight;
        this.enabled = enabled;
    }
    
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
     */
    @JsonIgnore
    public Optional<String> friendlyName() {
        return friendlyName;
    }

    /**
     * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
     */
    @JsonIgnore
    public Optional<String> target() {
        return target;
    }

    /**
     * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
     */
    @JsonIgnore
    public Optional<Long> priority() {
        return priority;
    }

    /**
     * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
     */
    @JsonIgnore
    public Optional<Long> weight() {
        return weight;
    }

    /**
     * Whether the Target is enabled.
     */
    @JsonIgnore
    public Optional<Boolean> enabled() {
        return enabled;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withFriendlyName(String friendlyName) {
        Utils.checkNotNull(friendlyName, "friendlyName");
        this.friendlyName = Optional.ofNullable(friendlyName);
        return this;
    }

    /**
     * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withFriendlyName(Optional<String> friendlyName) {
        Utils.checkNotNull(friendlyName, "friendlyName");
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withTarget(String target) {
        Utils.checkNotNull(target, "target");
        this.target = Optional.ofNullable(target);
        return this;
    }

    /**
     * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withTarget(Optional<String> target) {
        Utils.checkNotNull(target, "target");
        this.target = target;
        return this;
    }

    /**
     * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withPriority(long priority) {
        Utils.checkNotNull(priority, "priority");
        this.priority = Optional.ofNullable(priority);
        return this;
    }

    /**
     * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withPriority(Optional<Long> priority) {
        Utils.checkNotNull(priority, "priority");
        this.priority = priority;
        return this;
    }

    /**
     * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withWeight(long weight) {
        Utils.checkNotNull(weight, "weight");
        this.weight = Optional.ofNullable(weight);
        return this;
    }

    /**
     * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withWeight(Optional<Long> weight) {
        Utils.checkNotNull(weight, "weight");
        this.weight = weight;
        return this;
    }

    /**
     * Whether the Target is enabled.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withEnabled(boolean enabled) {
        Utils.checkNotNull(enabled, "enabled");
        this.enabled = Optional.ofNullable(enabled);
        return this;
    }

    /**
     * Whether the Target is enabled.
     */
    public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest withEnabled(Optional<Boolean> enabled) {
        Utils.checkNotNull(enabled, "enabled");
        this.enabled = enabled;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest other = (UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest) o;
        return 
            Objects.deepEquals(this.friendlyName, other.friendlyName) &&
            Objects.deepEquals(this.target, other.target) &&
            Objects.deepEquals(this.priority, other.priority) &&
            Objects.deepEquals(this.weight, other.weight) &&
            Objects.deepEquals(this.enabled, other.enabled);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            friendlyName,
            target,
            priority,
            weight,
            enabled);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest.class,
                "friendlyName", friendlyName,
                "target", target,
                "priority", priority,
                "weight", weight,
                "enabled", enabled);
    }
    
    public final static class Builder {
 
        private Optional<String> friendlyName = Optional.empty();
 
        private Optional<String> target = Optional.empty();
 
        private Optional<Long> priority = Optional.empty();
 
        private Optional<Long> weight = Optional.empty();
 
        private Optional<Boolean> enabled = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
         */
        public Builder friendlyName(String friendlyName) {
            Utils.checkNotNull(friendlyName, "friendlyName");
            this.friendlyName = Optional.ofNullable(friendlyName);
            return this;
        }

        /**
         * A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
         */
        public Builder friendlyName(Optional<String> friendlyName) {
            Utils.checkNotNull(friendlyName, "friendlyName");
            this.friendlyName = friendlyName;
            return this;
        }

        /**
         * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
         */
        public Builder target(String target) {
            Utils.checkNotNull(target, "target");
            this.target = Optional.ofNullable(target);
            return this;
        }

        /**
         * The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
         */
        public Builder target(Optional<String> target) {
            Utils.checkNotNull(target, "target");
            this.target = target;
            return this;
        }

        /**
         * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
         */
        public Builder priority(long priority) {
            Utils.checkNotNull(priority, "priority");
            this.priority = Optional.ofNullable(priority);
            return this;
        }

        /**
         * The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
         */
        public Builder priority(Optional<Long> priority) {
            Utils.checkNotNull(priority, "priority");
            this.priority = priority;
            return this;
        }

        /**
         * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
         */
        public Builder weight(long weight) {
            Utils.checkNotNull(weight, "weight");
            this.weight = Optional.ofNullable(weight);
            return this;
        }

        /**
         * The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
         */
        public Builder weight(Optional<Long> weight) {
            Utils.checkNotNull(weight, "weight");
            this.weight = weight;
            return this;
        }

        /**
         * Whether the Target is enabled.
         */
        public Builder enabled(boolean enabled) {
            Utils.checkNotNull(enabled, "enabled");
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * Whether the Target is enabled.
         */
        public Builder enabled(Optional<Boolean> enabled) {
            Utils.checkNotNull(enabled, "enabled");
            this.enabled = enabled;
            return this;
        }
        
        public UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest build() {
            return new UpdateConnectionPolicyTargetUpdateConnectionPolicyTargetRequest(
                friendlyName,
                target,
                priority,
                weight,
                enabled);
        }
    }
}

