/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class UpdateConnectionPolicyRequest {

    /**
     * The unique string that we created to identify the Connection Policy resource to update.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=Sid")
    private String sid;

    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    private Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody;

    @JsonCreator
    public UpdateConnectionPolicyRequest(
            String sid,
            Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody) {
        Utils.checkNotNull(sid, "sid");
        Utils.checkNotNull(requestBody, "requestBody");
        this.sid = sid;
        this.requestBody = requestBody;
    }
    
    public UpdateConnectionPolicyRequest(
            String sid) {
        this(sid, Optional.empty());
    }

    /**
     * The unique string that we created to identify the Connection Policy resource to update.
     */
    @JsonIgnore
    public String sid() {
        return sid;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody() {
        return (Optional<UpdateConnectionPolicyUpdateConnectionPolicyRequest>) requestBody;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The unique string that we created to identify the Connection Policy resource to update.
     */
    public UpdateConnectionPolicyRequest withSid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }

    public UpdateConnectionPolicyRequest withRequestBody(UpdateConnectionPolicyUpdateConnectionPolicyRequest requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.ofNullable(requestBody);
        return this;
    }

    public UpdateConnectionPolicyRequest withRequestBody(Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateConnectionPolicyRequest other = (UpdateConnectionPolicyRequest) o;
        return 
            Objects.deepEquals(this.sid, other.sid) &&
            Objects.deepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            sid,
            requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateConnectionPolicyRequest.class,
                "sid", sid,
                "requestBody", requestBody);
    }
    
    public final static class Builder {
 
        private String sid;
 
        private Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique string that we created to identify the Connection Policy resource to update.
         */
        public Builder sid(String sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = sid;
            return this;
        }

        public Builder requestBody(UpdateConnectionPolicyUpdateConnectionPolicyRequest requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = Optional.ofNullable(requestBody);
            return this;
        }

        public Builder requestBody(Optional<? extends UpdateConnectionPolicyUpdateConnectionPolicyRequest> requestBody) {
            Utils.checkNotNull(requestBody, "requestBody");
            this.requestBody = requestBody;
            return this;
        }
        
        public UpdateConnectionPolicyRequest build() {
            return new UpdateConnectionPolicyRequest(
                sid,
                requestBody);
        }
    }
}

