/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class UpdateSourceIpMappingRequestBuilder {

    private String sid;
    private Optional<? extends UpdateSourceIpMappingUpdateSourceIpMappingRequest> requestBody = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateSourceIpMapping sdk;

    public UpdateSourceIpMappingRequestBuilder(SDKMethodInterfaces.MethodCallUpdateSourceIpMapping sdk) {
        this.sdk = sdk;
    }

    public UpdateSourceIpMappingRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public UpdateSourceIpMappingRequestBuilder requestBody(UpdateSourceIpMappingUpdateSourceIpMappingRequest requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.of(requestBody);
        return this;
    }

    public UpdateSourceIpMappingRequestBuilder requestBody(Optional<? extends UpdateSourceIpMappingUpdateSourceIpMappingRequest> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
                
    public UpdateSourceIpMappingRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public UpdateSourceIpMappingRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public UpdateSourceIpMappingResponse call() throws Exception {

        return sdk.updateSourceIpMapping(
            sid,
            requestBody,
            serverURL);
    }
}
