/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class UpdateIpRecordRequestBuilder {

    private String sid;
    private Optional<? extends UpdateIpRecordUpdateIpRecordRequest> requestBody = Optional.empty();
    private Optional<String> serverURL = Optional.empty();
    private final SDKMethodInterfaces.MethodCallUpdateIpRecord sdk;

    public UpdateIpRecordRequestBuilder(SDKMethodInterfaces.MethodCallUpdateIpRecord sdk) {
        this.sdk = sdk;
    }

    public UpdateIpRecordRequestBuilder sid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }
                
    public UpdateIpRecordRequestBuilder requestBody(UpdateIpRecordUpdateIpRecordRequest requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = Optional.of(requestBody);
        return this;
    }

    public UpdateIpRecordRequestBuilder requestBody(Optional<? extends UpdateIpRecordUpdateIpRecordRequest> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }
                
    public UpdateIpRecordRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public UpdateIpRecordRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public UpdateIpRecordResponse call() throws Exception {

        return sdk.updateIpRecord(
            sid,
            requestBody,
            serverURL);
    }
}
