/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * VoiceFallbackMethod - The HTTP method we should use to call `voice_fallback_url`. Can be: `GET` or `POST`.
 */
public enum VoiceFallbackMethod {
    GET("GET"),
    POST("POST");

    @JsonValue
    private final String value;

    private VoiceFallbackMethod(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<VoiceFallbackMethod> fromValue(String value) {
        for (VoiceFallbackMethod o: VoiceFallbackMethod.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
