/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class VoiceV1IpRecord {

    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("account_sid")
    private JsonNullable<String> accountSid;

    /**
     * The unique string that we created to identify the IP Record resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sid")
    private JsonNullable<String> sid;

    /**
     * The string that you assigned to describe the resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("friendly_name")
    private JsonNullable<String> friendlyName;

    /**
     * An IP address in dotted decimal notation, IPv4 only.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ip_address")
    private JsonNullable<String> ipAddress;

    /**
     * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cidr_prefix_length")
    private Optional<Long> cidrPrefixLength;

    /**
     * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("date_created")
    private JsonNullable<OffsetDateTime> dateCreated;

    /**
     * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("date_updated")
    private JsonNullable<OffsetDateTime> dateUpdated;

    /**
     * The absolute URL of the resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    private JsonNullable<String> url;

    @JsonCreator
    public VoiceV1IpRecord(
            @JsonProperty("account_sid") JsonNullable<String> accountSid,
            @JsonProperty("sid") JsonNullable<String> sid,
            @JsonProperty("friendly_name") JsonNullable<String> friendlyName,
            @JsonProperty("ip_address") JsonNullable<String> ipAddress,
            @JsonProperty("cidr_prefix_length") Optional<Long> cidrPrefixLength,
            @JsonProperty("date_created") JsonNullable<OffsetDateTime> dateCreated,
            @JsonProperty("date_updated") JsonNullable<OffsetDateTime> dateUpdated,
            @JsonProperty("url") JsonNullable<String> url) {
        Utils.checkNotNull(accountSid, "accountSid");
        Utils.checkNotNull(sid, "sid");
        Utils.checkNotNull(friendlyName, "friendlyName");
        Utils.checkNotNull(ipAddress, "ipAddress");
        Utils.checkNotNull(cidrPrefixLength, "cidrPrefixLength");
        Utils.checkNotNull(dateCreated, "dateCreated");
        Utils.checkNotNull(dateUpdated, "dateUpdated");
        Utils.checkNotNull(url, "url");
        this.accountSid = accountSid;
        this.sid = sid;
        this.friendlyName = friendlyName;
        this.ipAddress = ipAddress;
        this.cidrPrefixLength = cidrPrefixLength;
        this.dateCreated = dateCreated;
        this.dateUpdated = dateUpdated;
        this.url = url;
    }
    
    public VoiceV1IpRecord() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
     */
    @JsonIgnore
    public JsonNullable<String> accountSid() {
        return accountSid;
    }

    /**
     * The unique string that we created to identify the IP Record resource.
     */
    @JsonIgnore
    public JsonNullable<String> sid() {
        return sid;
    }

    /**
     * The string that you assigned to describe the resource.
     */
    @JsonIgnore
    public JsonNullable<String> friendlyName() {
        return friendlyName;
    }

    /**
     * An IP address in dotted decimal notation, IPv4 only.
     */
    @JsonIgnore
    public JsonNullable<String> ipAddress() {
        return ipAddress;
    }

    /**
     * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
     */
    @JsonIgnore
    public Optional<Long> cidrPrefixLength() {
        return cidrPrefixLength;
    }

    /**
     * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    @JsonIgnore
    public JsonNullable<OffsetDateTime> dateCreated() {
        return dateCreated;
    }

    /**
     * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    @JsonIgnore
    public JsonNullable<OffsetDateTime> dateUpdated() {
        return dateUpdated;
    }

    /**
     * The absolute URL of the resource.
     */
    @JsonIgnore
    public JsonNullable<String> url() {
        return url;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
     */
    public VoiceV1IpRecord withAccountSid(String accountSid) {
        Utils.checkNotNull(accountSid, "accountSid");
        this.accountSid = JsonNullable.of(accountSid);
        return this;
    }

    /**
     * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
     */
    public VoiceV1IpRecord withAccountSid(JsonNullable<String> accountSid) {
        Utils.checkNotNull(accountSid, "accountSid");
        this.accountSid = accountSid;
        return this;
    }

    /**
     * The unique string that we created to identify the IP Record resource.
     */
    public VoiceV1IpRecord withSid(String sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = JsonNullable.of(sid);
        return this;
    }

    /**
     * The unique string that we created to identify the IP Record resource.
     */
    public VoiceV1IpRecord withSid(JsonNullable<String> sid) {
        Utils.checkNotNull(sid, "sid");
        this.sid = sid;
        return this;
    }

    /**
     * The string that you assigned to describe the resource.
     */
    public VoiceV1IpRecord withFriendlyName(String friendlyName) {
        Utils.checkNotNull(friendlyName, "friendlyName");
        this.friendlyName = JsonNullable.of(friendlyName);
        return this;
    }

    /**
     * The string that you assigned to describe the resource.
     */
    public VoiceV1IpRecord withFriendlyName(JsonNullable<String> friendlyName) {
        Utils.checkNotNull(friendlyName, "friendlyName");
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * An IP address in dotted decimal notation, IPv4 only.
     */
    public VoiceV1IpRecord withIpAddress(String ipAddress) {
        Utils.checkNotNull(ipAddress, "ipAddress");
        this.ipAddress = JsonNullable.of(ipAddress);
        return this;
    }

    /**
     * An IP address in dotted decimal notation, IPv4 only.
     */
    public VoiceV1IpRecord withIpAddress(JsonNullable<String> ipAddress) {
        Utils.checkNotNull(ipAddress, "ipAddress");
        this.ipAddress = ipAddress;
        return this;
    }

    /**
     * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
     */
    public VoiceV1IpRecord withCidrPrefixLength(long cidrPrefixLength) {
        Utils.checkNotNull(cidrPrefixLength, "cidrPrefixLength");
        this.cidrPrefixLength = Optional.ofNullable(cidrPrefixLength);
        return this;
    }

    /**
     * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
     */
    public VoiceV1IpRecord withCidrPrefixLength(Optional<Long> cidrPrefixLength) {
        Utils.checkNotNull(cidrPrefixLength, "cidrPrefixLength");
        this.cidrPrefixLength = cidrPrefixLength;
        return this;
    }

    /**
     * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    public VoiceV1IpRecord withDateCreated(OffsetDateTime dateCreated) {
        Utils.checkNotNull(dateCreated, "dateCreated");
        this.dateCreated = JsonNullable.of(dateCreated);
        return this;
    }

    /**
     * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    public VoiceV1IpRecord withDateCreated(JsonNullable<OffsetDateTime> dateCreated) {
        Utils.checkNotNull(dateCreated, "dateCreated");
        this.dateCreated = dateCreated;
        return this;
    }

    /**
     * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    public VoiceV1IpRecord withDateUpdated(OffsetDateTime dateUpdated) {
        Utils.checkNotNull(dateUpdated, "dateUpdated");
        this.dateUpdated = JsonNullable.of(dateUpdated);
        return this;
    }

    /**
     * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
     */
    public VoiceV1IpRecord withDateUpdated(JsonNullable<OffsetDateTime> dateUpdated) {
        Utils.checkNotNull(dateUpdated, "dateUpdated");
        this.dateUpdated = dateUpdated;
        return this;
    }

    /**
     * The absolute URL of the resource.
     */
    public VoiceV1IpRecord withUrl(String url) {
        Utils.checkNotNull(url, "url");
        this.url = JsonNullable.of(url);
        return this;
    }

    /**
     * The absolute URL of the resource.
     */
    public VoiceV1IpRecord withUrl(JsonNullable<String> url) {
        Utils.checkNotNull(url, "url");
        this.url = url;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VoiceV1IpRecord other = (VoiceV1IpRecord) o;
        return 
            Objects.deepEquals(this.accountSid, other.accountSid) &&
            Objects.deepEquals(this.sid, other.sid) &&
            Objects.deepEquals(this.friendlyName, other.friendlyName) &&
            Objects.deepEquals(this.ipAddress, other.ipAddress) &&
            Objects.deepEquals(this.cidrPrefixLength, other.cidrPrefixLength) &&
            Objects.deepEquals(this.dateCreated, other.dateCreated) &&
            Objects.deepEquals(this.dateUpdated, other.dateUpdated) &&
            Objects.deepEquals(this.url, other.url);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            accountSid,
            sid,
            friendlyName,
            ipAddress,
            cidrPrefixLength,
            dateCreated,
            dateUpdated,
            url);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VoiceV1IpRecord.class,
                "accountSid", accountSid,
                "sid", sid,
                "friendlyName", friendlyName,
                "ipAddress", ipAddress,
                "cidrPrefixLength", cidrPrefixLength,
                "dateCreated", dateCreated,
                "dateUpdated", dateUpdated,
                "url", url);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> accountSid = JsonNullable.undefined();
 
        private JsonNullable<String> sid = JsonNullable.undefined();
 
        private JsonNullable<String> friendlyName = JsonNullable.undefined();
 
        private JsonNullable<String> ipAddress = JsonNullable.undefined();
 
        private Optional<Long> cidrPrefixLength;
 
        private JsonNullable<OffsetDateTime> dateCreated = JsonNullable.undefined();
 
        private JsonNullable<OffsetDateTime> dateUpdated = JsonNullable.undefined();
 
        private JsonNullable<String> url = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
         */
        public Builder accountSid(String accountSid) {
            Utils.checkNotNull(accountSid, "accountSid");
            this.accountSid = JsonNullable.of(accountSid);
            return this;
        }

        /**
         * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
         */
        public Builder accountSid(JsonNullable<String> accountSid) {
            Utils.checkNotNull(accountSid, "accountSid");
            this.accountSid = accountSid;
            return this;
        }

        /**
         * The unique string that we created to identify the IP Record resource.
         */
        public Builder sid(String sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = JsonNullable.of(sid);
            return this;
        }

        /**
         * The unique string that we created to identify the IP Record resource.
         */
        public Builder sid(JsonNullable<String> sid) {
            Utils.checkNotNull(sid, "sid");
            this.sid = sid;
            return this;
        }

        /**
         * The string that you assigned to describe the resource.
         */
        public Builder friendlyName(String friendlyName) {
            Utils.checkNotNull(friendlyName, "friendlyName");
            this.friendlyName = JsonNullable.of(friendlyName);
            return this;
        }

        /**
         * The string that you assigned to describe the resource.
         */
        public Builder friendlyName(JsonNullable<String> friendlyName) {
            Utils.checkNotNull(friendlyName, "friendlyName");
            this.friendlyName = friendlyName;
            return this;
        }

        /**
         * An IP address in dotted decimal notation, IPv4 only.
         */
        public Builder ipAddress(String ipAddress) {
            Utils.checkNotNull(ipAddress, "ipAddress");
            this.ipAddress = JsonNullable.of(ipAddress);
            return this;
        }

        /**
         * An IP address in dotted decimal notation, IPv4 only.
         */
        public Builder ipAddress(JsonNullable<String> ipAddress) {
            Utils.checkNotNull(ipAddress, "ipAddress");
            this.ipAddress = ipAddress;
            return this;
        }

        /**
         * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
         */
        public Builder cidrPrefixLength(long cidrPrefixLength) {
            Utils.checkNotNull(cidrPrefixLength, "cidrPrefixLength");
            this.cidrPrefixLength = Optional.ofNullable(cidrPrefixLength);
            return this;
        }

        /**
         * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
         */
        public Builder cidrPrefixLength(Optional<Long> cidrPrefixLength) {
            Utils.checkNotNull(cidrPrefixLength, "cidrPrefixLength");
            this.cidrPrefixLength = cidrPrefixLength;
            return this;
        }

        /**
         * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
         */
        public Builder dateCreated(OffsetDateTime dateCreated) {
            Utils.checkNotNull(dateCreated, "dateCreated");
            this.dateCreated = JsonNullable.of(dateCreated);
            return this;
        }

        /**
         * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
         */
        public Builder dateCreated(JsonNullable<OffsetDateTime> dateCreated) {
            Utils.checkNotNull(dateCreated, "dateCreated");
            this.dateCreated = dateCreated;
            return this;
        }

        /**
         * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
         */
        public Builder dateUpdated(OffsetDateTime dateUpdated) {
            Utils.checkNotNull(dateUpdated, "dateUpdated");
            this.dateUpdated = JsonNullable.of(dateUpdated);
            return this;
        }

        /**
         * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
         */
        public Builder dateUpdated(JsonNullable<OffsetDateTime> dateUpdated) {
            Utils.checkNotNull(dateUpdated, "dateUpdated");
            this.dateUpdated = dateUpdated;
            return this;
        }

        /**
         * The absolute URL of the resource.
         */
        public Builder url(String url) {
            Utils.checkNotNull(url, "url");
            this.url = JsonNullable.of(url);
            return this;
        }

        /**
         * The absolute URL of the resource.
         */
        public Builder url(JsonNullable<String> url) {
            Utils.checkNotNull(url, "url");
            this.url = url;
            return this;
        }
        
        public VoiceV1IpRecord build() {
            if (cidrPrefixLength == null) {
                cidrPrefixLength = _SINGLETON_VALUE_CidrPrefixLength.value();
            }            return new VoiceV1IpRecord(
                accountSid,
                sid,
                friendlyName,
                ipAddress,
                cidrPrefixLength,
                dateCreated,
                dateUpdated,
                url);
        }

        private static final LazySingletonValue<Optional<Long>> _SINGLETON_VALUE_CidrPrefixLength =
                new LazySingletonValue<>(
                        "cidr_prefix_length",
                        "0",
                        new TypeReference<Optional<Long>>() {});
    }
}

