/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package org.openapis.openapi.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes {

    /**
     * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prefix")
    private JsonNullable<String> prefix;

    @JsonCreator
    public VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes(
            @JsonProperty("prefix") JsonNullable<String> prefix) {
        Utils.checkNotNull(prefix, "prefix");
        this.prefix = prefix;
    }
    
    public VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes() {
        this(JsonNullable.undefined());
    }

    /**
     * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
     */
    @JsonIgnore
    public JsonNullable<String> prefix() {
        return prefix;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
     */
    public VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes withPrefix(String prefix) {
        Utils.checkNotNull(prefix, "prefix");
        this.prefix = JsonNullable.of(prefix);
        return this;
    }

    /**
     * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
     */
    public VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes withPrefix(JsonNullable<String> prefix) {
        Utils.checkNotNull(prefix, "prefix");
        this.prefix = prefix;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes other = (VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes) o;
        return 
            Objects.deepEquals(this.prefix, other.prefix);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            prefix);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes.class,
                "prefix", prefix);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> prefix = JsonNullable.undefined();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
         */
        public Builder prefix(String prefix) {
            Utils.checkNotNull(prefix, "prefix");
            this.prefix = JsonNullable.of(prefix);
            return this;
        }

        /**
         * A prefix is a contiguous number range for a block of E.164 numbers that includes the E.164 assigned country code. For example, a North American Numbering Plan prefix like `+1510720` written like `+1(510) 720` matches all numbers inclusive from `+1(510) 720-0000` to `+1(510) 720-9999`.
         */
        public Builder prefix(JsonNullable<String> prefix) {
            Utils.checkNotNull(prefix, "prefix");
            this.prefix = prefix;
            return this;
        }
        
        public VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes build() {
            return new VoiceV1DialingPermissionsDialingPermissionsCountryDialingPermissionsHrsPrefixes(
                prefix);
        }
    }
}

